In [1]:
import torch
import torch.nn as nn


In [11]:
input_dim = 5
hidden_dim = 10
n_layers = 12

lstm_layer = nn.LSTM(input_dim, hidden_dim, n_layers, batch_first=True)

In [12]:
lstm_layer = nn.LSTM(input_dim, hidden_dim, n_layers, batch_first=True)


In [13]:
batch_size = 1
seq_len = 1

inp = torch.randn(batch_size, seq_len, input_dim)
hidden_state = torch.randn(n_layers, batch_size, hidden_dim)
cell_state = torch.randn(n_layers, batch_size, hidden_dim)
hidden = (hidden_state, cell_state)
print(inp)
print(hidden_state)
print(cell_state)

tensor([[[ 0.4132, -1.0812, -0.1222,  0.1265, -0.6428]]])
tensor([[[ 0.7958, -0.7464,  0.5637,  1.1121,  0.5694,  0.4909, -0.4781,
           0.1127, -0.5833,  1.3827]],

        [[ 1.2221, -0.3230, -0.0822,  0.5305,  1.9607, -0.2715, -0.1535,
           0.8534, -0.1527,  0.6682]],

        [[ 0.8450,  0.7944, -0.0297, -1.0651, -0.3538, -1.1068, -0.0970,
          -1.2039,  0.9261, -0.1844]],

        [[-0.0853,  0.7480, -0.1447,  2.1646,  0.7375, -0.6135,  0.2734,
          -0.9048,  0.4975, -0.3655]],

        [[-0.2930, -1.3718, -0.0210,  0.1849, -0.9311,  0.2490,  0.6823,
           0.1017, -0.9010, -0.1020]],

        [[-0.6550,  1.1789,  0.1653,  0.9993,  0.8183, -1.8222,  0.5915,
           0.0487,  0.5040,  0.1276]],

        [[ 0.0103, -0.4388,  1.8847,  0.2968,  2.2613,  3.0415, -0.7781,
          -0.0514,  1.6969,  0.4631]],

        [[ 1.1979,  1.0914, -1.1722, -1.5081,  1.1057,  0.9183, -0.8138,
           0.8024,  0.5878, -0.4444]],

        [[ 1.0149,  0.8376, -0.1598,  

In [14]:
out, hidden = lstm_layer(inp, hidden)
print("Output shape: ", out.shape)
print("Hidden: ", hidden)

Output shape:  torch.Size([1, 1, 10])
Hidden:  (tensor([[[ 0.4291, -0.0729, -0.2394,  0.0433, -0.0811,  0.2463,  0.4998,
          -0.1200,  0.1310,  0.3160]],

        [[ 0.4368, -0.2478,  0.1046,  0.1976, -0.1265,  0.2763,  0.3282,
           0.1281, -0.2516,  0.4709]],

        [[ 0.1224, -0.2109, -0.3552,  0.1585, -0.1481,  0.4909, -0.2201,
           0.1543, -0.2835, -0.4016]],

        [[ 0.2305,  0.2872,  0.3435,  0.1076, -0.5096,  0.3074, -0.1955,
           0.0411, -0.0633, -0.0454]],

        [[-0.0376, -0.0828, -0.1974, -0.0726,  0.1652, -0.1367, -0.2559,
          -0.2991, -0.3009, -0.1192]],

        [[ 0.0612, -0.2567,  0.1148,  0.2124,  0.1606, -0.0930,  0.1084,
           0.3651, -0.1652, -0.0737]],

        [[ 0.2917,  0.3249, -0.1868,  0.0838,  0.0096, -0.2766,  0.0505,
          -0.0307,  0.1963,  0.3513]],

        [[-0.0568,  0.2376,  0.3155,  0.2017, -0.2862,  0.0312, -0.2004,
          -0.4120,  0.2955,  0.3696]],

        [[-0.1383, -0.1147,  0.3951,  0.0678, -0

In [10]:
seq_len = 3
inp = torch.randn(batch_size, seq_len, input_dim)
out, hidden = lstm_layer(inp, hidden)
print(inp)
print(out.shape)

tensor([[[ 0.3807,  0.2682, -0.8388, -0.5764,  0.5126],
         [-1.2332,  0.6599,  0.9149,  1.2497, -2.0541],
         [-0.4246,  1.8996, -2.3256, -1.1173,  0.3092]]])
torch.Size([1, 3, 10])
